# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
    desc "Description of what the lane does"
    lane :custom_lane do
        # add actions here: https://docs.fastlane.tools/actions
    end

    desc "Unit Testing lane"
    lane :tests do
        run_tests(scheme: "XMonstersTests")
    end

    desc "Upload metadata only (no build, no screenshots)"
    lane :upload_metadata do
        deliver(
            skip_screenshots:true,
            skip_binary_upload:true,
            submit_for_review:false,
            automatic_release:false,
            phased_release:true,
            precheck_include_in_app_purchases:false
            )
    end
end
